### ISSUE TITLE
Broken image link

### ISSUE THREAD

**Issue by andreic-ensemble** [radiantlogic-v8/documentation-new#17]
Broken link here:

https://github.com/radiantlogic-v8/documentation-new/blob/4c0f6856accba2d05c691fed736249dc215ac5c0/documentation/sys-admin-guide/concepts.md?plain=1#L934

**Comment by jeffduerksen** [comment]
Updated concepts chapter in Sys Admin Guide and uploaded image2.31.jpg to both v7.4 and v8 branches.
