### ISSUE TITLE
Broken image link and incomplete alt

### ISSUE THREAD

**Issue by andreic-ensemble** [radiantlogic-v8/documentation-new#18]
Broken image link and incomplete alt here: https://github.com/radiantlogic-v8/documentation-new/blob/e64f9fc962f5421360af1ac08f872654afc0c842/documentation/deployment-and-tuning-guide/00-preface.md?plain=1#L70

**Comment by jeffduerksen** [comment]
Updated v7.4 Preface chapter in Deployment and Tuning Guide. Image now displays.
