### ISSUE TITLE
Broken image links

### ISSUE THREAD

**Issue by andreic-ensemble** [radiantlogic-v8/documentation-new#19]
incomplete alt: https://github.com/radiantlogic-v8/documentation-new/blob/e64f9fc962f5421360af1ac08f872654afc0c842/documentation/monitoring-and-reporting-guide/01-monitoring.md?plain=1#L213

Broken link: https://github.com/radiantlogic-v8/documentation-new/blob/e64f9fc962f5421360af1ac08f872654afc0c842/documentation/monitoring-and-reporting-guide/01-monitoring.md?plain=1#L29

incomplete alt: https://github.com/radiantlogic-v8/documentation-new/blob/e64f9fc962f5421360af1ac08f872654afc0c842/documentation/monitoring-and-reporting-guide/01-monitoring.md?plain=1#L395

**Comment by jeffduerksen** [comment]
Hi Andrei, I fixed the broken expert-mode image link. But in Visual Studio Code and in Github, images 1.8.jpg and 1.16.jpg display for me. Can you give me some more information about what seems to be wrong with those images so I can investigate further?

**Comment by andreic-ensemble** [comment]
Thank you, it is working now, I'll close the issue.
