### ISSUE TITLE
Missing alts in 03-virtual-view-of-ldap-backends

### ISSUE THREAD

**Issue by andreic-ensemble** [radiantlogic-v8/documentation-new#20]
incomplete image alts in: https://github.com/radiantlogic-v8/documentation-new/blob/r1-saas/documentation/namespace-configuration-guide/03-virtual-view-of-ldap-backends.md

broken image link: https://github.com/radiantlogic-v8/documentation-new/blob/99068eb404b6ecbd87a525b5ebcac82babf9b252/documentation/namespace-configuration-guide/03-virtual-view-of-ldap-backends.md?plain=1#L757

**Comment by jeffduerksen** [comment]
Updated v7.4 and v8 Namespace Configuration Guides.
