### ISSUE TITLE
Broken image link /sys-admin-guide-rebuild/05-creating-virtual-views

### ISSUE THREAD

**Issue by andreic-ensemble** [radiantlogic-v8/documentation-new#26]
Broken image link and incomplete image alts in page
https://github.com/radiantlogic-v8/documentation-new/blob/18058862e6680a11ab5133fca44a03ac9a2c33e4/documentation/sys-admin-guide-rebuild/05-creating-virtual-views.md?plain=1#L90

**Comment by jeffduerksen** [comment]
Updated Creating Virtual Views chapter of Sys Admin Guide.
